addSbtPlugin("com.eed3si9n"    % "sbt-assembly"    % "0.14.2")
addSbtPlugin("org.scoverage"   % "sbt-scoverage"   % "1.5.1")
addSbtPlugin("org.scoverage"   % "sbt-coveralls"   % "1.2.2")
addSbtPlugin("org.wartremover" % "sbt-wartremover" % "2.2.1")
addSbtPlugin("com.lucidchart"  % "sbt-scalafmt"    % "1.15")
